DATALOADER:
  K_TRANSFORMS: 2
  TRAIN_X:
    BATCH_SIZE: 64
  TEST:
    BATCH_SIZE: 64

OPTIM:
  NAME: 'sgd'
  LR: 0.05
  STEPSIZE: [800]
  MAX_EPOCH: 800
  LR_SCHEDULER: 'cosine'

TRAIN:
  COUNT_ITER: 'train_u'
  PRINT_FREQ: 20